
CREATE TABLE Client (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    uniqId INT AUTO_INCREMENT PRIMARY KEY
    phoneNumber INT NOT NULL
);

CREATE TABLE RequestOrder (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    mechanic VARCHAR(255) NOT NULL,
    service VARCHAR(255) NOT NULL,
    bikeModel VARCHAR(255) NOT NULL,
    uniqId INT NOT NULL
);

CREATE TABLE Services (
    serviceId INT AUTO_INCREMENT PRIMARY KEY,
    smallservice INT NOT NULL,
    fullservice INT NOT NULL,
    repair INT NOT NULL
);

CREATE TABLE Bike (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    bike VARCHAR(255) NOT NULL,
    modelType VARCHAR(255) NOT NULL,
    serialNumber INT NOT NULL
);